apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex-app
        image: linuxserver/plex
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpu: 1
          requests:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpu: 1
#            gpu.intel.com/i915: 1
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
        env:
        - name: ADVERTISE_IP
          value: "http://192.168.1.237:32400/"
        - name: VERSION
          value: "latest"
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: TZ
          value: "America/Toronto"
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-claim-token
              key: token
        volumeMounts:
        - name: plex-data
          mountPath: /config
        - name: plex-media
          mountPath: /media
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-pv-config-claim
      - name: plex-media
        persistentVolumeClaim:
          claimName: plex-pv-media-claim
