apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-media-volume
  namespace: plex
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /export/Videos
    server: 192.168.1.254
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pv-media-claim
  namespace: plex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
